### ISSUE TITLE
songs not listed

### ISSUE THREAD

**Issue by sedrubal** [notandy/ympd#27] opened 2014-08-13 18:47 UTC
I detected, that some songs are not listet in the database-view of ympd, but the database of mpd contains them, because ncmpc lists them. Unfortunately I did't see something special on this songs...

**Comment by yjokawa** [comment] 2015-09-23 08:52
Hi,

First of all, thank you for this great mpd client!

I also have the same trouble.
When I first build ympd in March, the binary works completely.
However, when I build it in August, the bug appeared.
I suppose that mongoose 5.6 causes this problem, but I don't have any direct evidence.

Regards,
yjo

**Comment by yjokawa** [comment] 2015-10-15 01:43
When returning no song info, mpd gives the following error:
MPD mpd_send_list_meta: Not found
MPD connection failed.

**Comment by tedigh** [comment] 2016-01-02 08:06
Hi,
In my case, the folders / songs those contain "comma" in their names is missing.
I find the calls of strtok() in mpd_client.c do wrong with them.
The removal of  4ba3e0b70ffa0f47d99a13d7758e613628c4a607 seems to be the solution.

**Comment by LordMyschkin** [comment] 2016-01-02 22:54
thats exactly the same bug I filed under issue #107.
Commas may be part of the problem, but I also do not see   a file named "01_-_johannes_brahms_-_klavierkonzert_nr._1-_maestoso.mp3"
If you want to reproduce the problem, I send you the link to my library - or some of my files...
Please let me know if I can be of any help - or point me to the best IDE to debug ympd on the raspberry....

**Comment by tedigh** [comment] 2016-01-03 04:18
I found at least some special characters in the directory names cause this issue.
try the both.
sed -i 's/codeURI/codeURIComponent/g' htdocs/js/mpd.js
revert 4ba3e0b  (merge conflict need to be fixed by hand)

**Comment by SuperBFG7** [comment] 2016-01-25 12:31
I just ran into this as well and created a fix: #116 
it's already included in my fork

**Comment by LordMyschkin** [comment] 2016-01-25 18:52
Thank you so much, @SuperBFG7; it works finally!

**Comment by SuperBFG7** [comment] 2016-01-25 19:24
You're welcome. Thanks @tedigh for pointing me in the right direction.

**Comment by yjokawa** [comment] 2016-01-26 03:34
Thank you, SuperBFG7!
I also succeeded.  You fix works very well!!

**Comment by notandy** [comment] 2016-02-14 15:12
should be fixed now

**Closed by notandy** 2016-02-14 15:12 UTC
Labels: bug
