### ISSUE TITLE
volume slider doesn't work

### ISSUE THREAD

**Issue by typhoon71** [notandy/ympd#61] opened 2015-03-26 09:21 UTC
well, ympd works fine, but the volume slider seems to only have 2 possible values: max volume and a really low volume setting.
other mpd client seems to be fine to me.
can this be fixed/investigated?

**Comment by notandy** [comment] 2015-03-29 15:23
Do you use an old/mobile browser? What one?

**Comment by typhoon71** [comment] 2015-03-29 15:42
I forgot to post it that I fixed it using mixer = software in mpd config.
I don't know why other client were fine without this fix; I tested with auremo, on windows 7.
mpd and ympd are on a headless raspberry pi 1 running raspian hf, the browser is firefox 36, same lan.

I'm using the code from https://github.com/notandy/ympd/issues/46, but I don't know if it's realated.

**Comment by notandy** [comment] 2015-03-29 15:50
Hrm. very strange. It sounds like a problem with the mpd mixer controls, but then it shouldn't work in other clients. My tests with raspberry pi's didn't showed any problems. I don't think #46 breaks anything with the mixer controls.

I close this bug since I can't reproduce it, if you could trace the source of this bug feel free to reopen it.

**Closed by notandy** 2015-03-29 15:50 UTC
Labels: bug
