### ISSUE TITLE
Feature Request: Enable/Disable - Audio Outputs 

### ISSUE THREAD

**Issue by rhoering** [notandy/ympd#60] opened 2015-03-20 04:28 UTC
The feature would allow a user to us the web GUI to:

a) Enable Output 2 just like "mpc enable 2"
b) Disable Output 1 just like "mpc disable 1"

**Comment by notandy** [comment] 2015-03-29 15:23
duplicate of #50

**Closed by notandy** 2015-03-29 15:23 UTC
